### ISSUE TITLE
取消 跳转至页面顶部的 小钢铁侠

### ISSUE THREAD

**Issue by GengZ** [YenYuHsuan/hexo-theme-beantech#13]
hi，每个页面右下角有一个小钢铁侠，点击返回页面顶部，请问这个可以取消吗？

**Comment by YenYuHsuan** [comment]
@GengZ 
You can edit the file `hexo-theme-beantech/themes/beantech/layout/layout.ejs`:
comment out the object from `<a id="rocket" href="#top" class=""></a>` to  `<!--<a id="rocket" href="#top" class=""></a>-->` 
then the iron man will gone
Peace!
