### ISSUE TITLE
How to hide the toc-nav-number ?

### ISSUE THREAD

**Issue by YenYuHsuan** [YenYuHsuan/hexo-theme-beantech#14]
Depends on the user writing habit, some of u like to write title with numbers

> # 1. H1
> ## 1-1 H2

but after generating toc, it'll number the title twice

> 1.1. H1
>&nbsp;&nbsp;&nbsp;&nbsp; 1.1 1-1 H2 

so create an on/off variable to show/hide toc-nav-number can be the solution

thx to @huweihuang for finding out this issue

**Comment by YenYuHsuan** [comment]
@huweihuang i think you can modify the file `hexo-theme-beantech/themes/beantech/layout/_partial/toc.ejs` like:
```ejs
<!-- Table of Contents -->
<% if (page.catalog) { %>
    <!-- Add new code here -->
    <% if(!page.toc_nav_num){%>
      <style>
        span.toc-nav-number{
          display: none
        }
      </style>
    <% } %>

    <!-- the other code ... -->
<% } %>
```
then you may add another variable at your post
```yml
#  true: show nav number
# false: hide nav number
toc_nav_num: true
```

**Comment by huweihuang** [comment]
@YenYuHsuan 谢谢！该方法可解决目录序号重复的问题，代码已更新。另外提一个问题是当标题文字比较多的时候，目录文字会出现自动换行折叠，感觉排版不是很美观，希望可以调整子目录和父目录之间间隔的大小（目前间隔过大占用空间），我修改了theme/xxx/source/css/toc.styl中的 
```
.toc-nav-child 
     margin-left 0.3em
```
的数值发现没有生效。麻烦帮忙指导下，具体现象可以参考：http://www.huweihuang.com/article/kubernetes/kubernetes-architecture/ 右侧目录。

**Comment by YenYuHsuan** [comment]
@huweihuang it's not "not work" cause the browser default padding of HTML list tag `<ol> & <li>` are 40px in Chrome (css: `-webkit-padding-start: 40px;`).
and there is another question, the property `padding` can't be minus to decrease the indent.
but i found out the other solution, you may use property `margin-left: -2em;` to decrease indent.
here is the [solution](https://stackoverflow.com/questions/29307357/get-rid-of-webkit-padding-start-40px) i found.

**Comment by huweihuang** [comment]
@YenYuHsuan perfect, thanks！it works for me.
