### ISSUE TITLE
文章内目录以及回到顶部出现问题

### ISSUE THREAD

**Issue by KerwinCode** [YenYuHsuan/hexo-theme-beantech#16]
首先，感谢您提供这么漂亮的主题。
但是我在使用的过程中出现了一些问题。

文章内目录点击无法跳转，锚点变为 `#undefined` ，正常情况应该是#子标题，还有当页面向下滚动时，目录会随着页面内容滚动，不能始终保持在页面右侧。还有就是没有显示回到顶部的按钮，也就是展示页面中的iron man图标。

这些问题，我尝试了Google到的一些方法，但还是没能解决。我不知道哪里出了问题，以及如何有效地解决。

`hexo`版本信息 以及 `package.json`的内容
```
$ hexo version
hexo: 3.4.4
hexo-cli: 1.0.4
os: Linux 4.13.0-26-generic linux x64
http_parser: 2.5.0
node: 4.2.6
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 55.1
modules: 46
openssl: 1.0.2g-fips
```

```
$ cat package.json 
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.1.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-seo-friendly-sitemap": "0.0.20",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-toc": "^1.1.0"
  }
}
```

希望能够得到您的帮助！

**Comment by KerwinCode** [comment]
关于 `toc` 的锚点变为 `#undefined` ，已经 Closed 的 Issue #11 中给出了解决办法。 New这个Issue的时候没有注意到 :sweat_smile:

**Comment by KerwinCode** [comment]
还有文章内目录会随着页面内容滚动，不能浮动显示 以及 回到顶部按钮不显示的问题，通过 Chrome 的 F12开发者工具可以查看到，是由于 `toc.js` 和 `totop.js` 加载失败造成的。我把 `config.yml` 中 `url` 后的子目录去掉，把 `root` 改为 `/` 后 ，这几个js文件就可以找到了，问题就解决了。

但之前的情况，当网站存放在子目录时，例如 `url` 设为 `http://website.com/blog` 并把 `root` 设为 `/blog/` 时，就会存在上述问题。

**Comment by YenYuHsuan** [comment]
@kerwin-hw Hi,
if you change the root path, you need to redirect all the import file path.
so I recommend you can keep it as my recent version.

but I have some advice for you in using `blog/` file to put your posts.
first, you can create a new variable in `config.yml` like
```yml
root: /
blog_dir: /blog/
```
then you modify `post.ejs` by replacing all the variable `<%- config.root %>` into `<%- config.blog_dir %>`
then you can redirect all the blog post to `blog/xxx`
But this may cause another problem (or not).
you can try it and share with us your results 😄 
Peace!

**Comment by KerwinCode** [comment]
I tried to modify `post.ejs` according to the way you mentioned above.
And I moved all the posts to `blog/xxx` .  Everything worked normally without any problems.

But now, I don't feel that it's necessary to redirect posts to a subdirectory. It has been able to meet all my requirements.

Thank you for your reply :smile:
