### ISSUE TITLE
能增加valine评论功能吗？

### ISSUE THREAD

**Issue by HeXingye** [YenYuHsuan/hexo-theme-beantech#21]
多说用不了了，希望能增加一个valine的评论功能，谢谢博主！

**Comment by YenYuHsuan** [comment]
@HeXingye Hi~you may use [this solution](https://jayshao.com/disqus-to-valine/) to change Disqus to Valine!

**Comment by nqmysb** [comment]
我的添加了来必力 https://liaocan.top
