### ISSUE TITLE
categories页面应该如何配置？

### ISSUE THREAD

**Issue by xchz** [YenYuHsuan/hexo-theme-beantech#7]
[创建在导航添加categories后并没有解决这个issue[categories页面使用的是page模版](https://github.com/Kaijun/hexo-theme-huxblog/issues/57#issuecomment-312417339)

**Comment by xchz** [comment]
看了next主题的代码，在page模版里通过page.type判断页面类型`if(page.type === 'categories')`

**Comment by YenYuHsuan** [comment]
@xchz 我懂你意思了~
感謝你的回覆^__^

BTW
因為我個人沒特別需要一頁面顯示categories所以我沒特別製做這個page的模板
但若有需要，大家可以利用 xchz的方法 製做的categories模板
謝謝 :smile: 
Peace!
