### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by spring2613** [YenYuHsuan/hexo-theme-beantech#9]
Contents  长了以后就不显示了

**Comment by YenYuHsuan** [comment]
@spring2613 Hi, can i have some example?
i did not understand your problem

**Comment by spring2613** [comment]
![image](https://user-images.githubusercontent.com/9389212/30773594-547a8134-a0a6-11e7-836d-75fb0a15a8e8.png)

**Comment by YenYuHsuan** [comment]
@spring2613 oh! i see
i  have fixed the problem 👍  
here is the solution i use #10 :
1. Go find the css file which render the toc ( in my case the file is at: `./BeanTech/source/css/toc.styl`)
2. Verify the css code
change the attribute `overflow` from "hidden" to "auto", then the browser will auto decide to be scrollable or not. 
```styl
#toc
  width: inherit
  line-height 1em
  font-size 0.9em
  float left
  overflow: auto  // where i fixed the problem
  @media mq-mobile
    display: none
  @media mq-tablet
    display: none
```
3. Regenerate and Redeploy the whole project
`hexo g -d`
Done!
Thanks for reporting the error 💯 
Peace!
